### ISSUE TITLE
Bug en tabla de posiciones

### ISSUE THREAD

**Issue by MacarenaMiMa** [fraco-oxza/tankGame#136]
Al momento de crear la tabla de posiciones, la cantidad de muertes no se suma al tanque que mató a los demás tanques (como que las muertes se reparten), por ejemplo si un tanque hace 3 muertes, 2 de ellas se le atribuyen al tanque de otro color y la otra a otro tanque

**Comment by fraco-oxza** [comment]
Maca, ¿Arreglaste el problema?¿Qué era?
