### ISSUE TITLE
Los tanques caen más abajo del suelo

### ISSUE THREAD

**Issue by MacarenaMiMa** [fraco-oxza/tankGame#139]
Se probó haciendo un disparo y los tanques cayeron más abajo del suelo, a pesar de que la bala no tocó cerca de los tanques como para destruir el suelo

**Comment by MacarenaMiMa** [comment]
![Uploading Imagen1.png…]()

**Comment by fraco-oxza** [comment]
hola maca, no puedo ver la fotografia que subiste. 
![image](https://github.com/fraco-oxza/tankGame/assets/70904658/34938564-9d0b-4430-b4ba-3afd2470a8d4)

**Comment by fraco-oxza** [comment]
creo que tienes que esperar a que se suba, antes de apretar comentar

**Comment by MacarenaMiMa** [comment]
Hola, esta es la foto 
<img width="960" alt="image" src="https://github.com/fraco-oxza/tankGame/assets/143454403/bd30b122-af45-44a8-bbe0-8172edd295df">

**Comment by fraco-oxza** [comment]
No he podido saber que causa el bug, crearé una branch para añadir una función que verifique en cada disparo que los tanques estén colocados sobre el nivel de la tierra

**Comment by fraco-oxza** [comment]
![image](https://github.com/fraco-oxza/tankGame/assets/70904658/daf92eed-3a6b-42b9-aca7-619ee2abde10)
